include:
  - compose/networks.yml
  - compose/volumes.yml
  - compose/core-services.yml
  - compose/monitoring-services.yml
  - compose/threat-intelligence.yml
  - compose/misp-stack.yml
  - compose/siem-services.yml
  - compose/soar-services.yml
  - compose/edr-services.yml
  - compose/wazuh-stack.yml
  - compose/shuffle-stack.yml
